### ISSUE TITLE
Alternative SDK Flash Utility Distribution Method.

### ISSUE THREAD

**Issue by kyleparrott** [kubostech/kubos-sdk#77]
Right now we use bundled flash utilities and libraries which are not the most consistent in installation or running (thanks to SIP on osx 10.11+). This method isn't ideal as we are distributing both mac os and linux binaries in every single install. We are evaluating alternative methods for distributing our utilities and their library dependencies.

Bundled Flash Utilities (Binaries included in the sdk):

| Pros  | Cons |
| ------------- | ------------- |
| No External Downloads  | Unused binaries bloat sdk size (mac binaries not needed on linux and vice versa) |
|   | Manually Update build process each time a new binary utility/dependency is added  |
|   | Setting PATH / LD_LIBRARY_PATH Not reliable on mac os  |
|   | No api/Spawn subprocesses for flashing commands |

0Install 

| Pros  | Cons |
| ------------- | ------------- |
| Simplified build process | Version inconsistencies * (See below) - Potential support nightmare |
| Runtime management - 0install manages binary installation locations and running the binaries | Utilities not easily available to user (not in PATH) | 
| No special installation steps - dynamically downloads utility/dependencies when a command is run | General inconsistencies in docs and actual usage based on installed version |
| Has a JSON api |  I haven't gotten the JSON API to do anything useful so far |
* 0install version inconsistencies - Linux package managers distribute a half python/ half ocaml 0install implementation (v2.3.3) and on macos homebrew distributes a pure ocaml implementation ( v2.11.X) and mac ports distributes an older pure python implementation (v1.7)

Conda

| Pros  | Cons |
| ------------- | ------------- |
| Written in Python - API | No Run management - Spawn subprocesses for flashing commands | 
| Lots of community, clean docs and lots of support |  | 
| Plays nicely/ integrates easily in the Python pypi module world - not sure how relevant for distributing binaries this point is | 

Building our own download mechanism: 

| Pros | Cons |
| ------------- | ------------- |
| Would not require any additional installation pre-requisites | We have to build and maintain this part of the sdk | 
|  | Additional Step in installation of adding directories to PATH/LD_LIBRARY_PATH in .bashrc/.bash_profile

I am continuing to research and try to find the best alternatives for us. I appreciate any and everyone's input on making this decision. 

/cc @kubostech/devs

**Comment by kyleparrott** [comment]
On Friday, @davesims and I discussed this further and came to the conclusion, mac and linux specific builds with bundled flash utilities for their respective platform. 

There would be some new post-installation step such as the existing `kubos update` command (or extending the update command) that would additionally copy these utilities and libraries to a known location such as `/usr/local/share/kubos/bin`. 

In the docs there would be another installation step that would include adding this directory to the user's PATH/ LD_LIBRARY_PATH in the users .bashrc or .*rc file.

/cc @kubostech/devs

**Comment by davesims** [comment]
Per conversations & discovery over the last couple of days, in order to avoid multiple platform distributions as described by @kyleparrott above, instead move the flash utilities to the linux image, and mount and flash the device from there. This would entail moving from Docker to Vagrant/VirtualBox since Docker & OSX don't play nicely with USB devices.

**Comment by kyleparrott** [comment]
The switch to the [kubos-cli](https://github.com/kubostech/kubos-cli) has deprecated the kubos-sdk, so I am closing this issue.
