### ISSUE TITLE
Investigate tool delivery methods

### ISSUE THREAD

**Issue by rplauche** [kubostech/kubos-sdk#9]
As we expand the supported platforms/tools we may not want to package them all with the pypi module. I think it is worth investigating a method of downloading tools as they are needed.

The PlatformIO project does a good job of this - https://github.com/platformio/platformio.

https://github.com/platformio/platformio/blob/14da22f5ab8cf448e67c14301e930bff394f41b6/docs/userguide/platforms/cmd_install.rst

**Comment by rplauche** [comment]
http://0install.net/api-example.html

**Comment by kyleparrott** [comment]
Moved to [JIRA](https://kubostech.atlassian.net/browse/KUBOS-97)
